- name: Flush existing iptable rules in INPUT chain
  iptables:
    chain: INPUT
    flush: true

- name: Firewall rule INPUT - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  when: iptables.rules.input.allow_loopback

- name: Firewall rule INPUT - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  when: iptables.rules.input.allow_established_connections

- name: Firewall rule INPUT - allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
  when: iptables.rules.input.allow_icmp

- name: Firewall rule INPUT - allow port SSH traffic (Port "{{ ssh.Port }}")
  iptables:
    chain: INPUT
    destination_port: "{{ ssh.Port }}"
    jump: ACCEPT
    protocol: tcp
  when: iptables.rules.input.allow_ssh

- name: Firewall rule INPUT - allow additional ports
  iptables:
    chain: INPUT
    source: "{{ item.source | default('0.0.0.0/0') }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    protocol: "{{ item.protocol }}"
    comment: "{{ item.comment }}"
  with_items: "{{ iptables.rules.input.allow_additional_ports }}"

- name: Firewall rule INPUT - DROP everything else
  iptables:
    chain: INPUT
    jump: DROP
    protocol: all
